name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Docker build and push to github registry
      uses: opspresso/action-docker@master
      env:
        USERNAME: "f9uf"
        PASSWORD: ${{ secrets.HUB_PASSWORD }}
        REGISTRY: "docker.pkg.github.com"
        IMAGE_NAME: "goimage"
        TAG_NAME: "v0.0.1"
        LATEST: "true"
        DOCKERFILE: "Dockerfile"
