name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Login to registry
      run: echo ${{ secrets.HUB_PASSWORD }} | docker login docker.pkg.github.com -u ${{ secrets.HUB_USERNAME }} --password-stdin

    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}

    - name: Push image to registry
      run: docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}

